version: '3.8'

services:
  frontend:
    container_name: 'frontend-development'
    build:
      context: .
    command: yarn start
    volumes:
      - ./:/app/frontend/
    ports:
      - "3000:3000"
    stdin_open: true
